config/routes.rb
Reloaded::Application.routes.draw do

  use_doorkeeper

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  #devise_for :users, :controllers => { :registrations => "users/registrations",:sessions => "users/sessions" }
  
 #  devise_for :users, :controllers => { :registrations => "users/registrations", 
 #   :sessions=> 'users/sessions',:invitations => 'users/invitations', 
 #   :omniauth_callbacks=>'omniauth_callbacks' },
 #   :token_authentication_key => 'authentication_key'3333333333333333333333333

  resources :user_contacts, :users, :statuses, :efiles, :search, :contacts, :options, :invitations, :chats, :blocked_users, :channels, :channel_users, :shadow,
            :messages,:products,:carts,:cart_items,:ads,:orders,:feedbacks,:cart_products,:quotes,:quote_types,:authors,:links, :uploads, :countries, :posts,:domains,:mail_accounts,:pictures,:alias_maps,:mini_post_comments, :timeline, :mini_post_comment_likings,:tags, :updates, :post_tags, :requests, :mini_post_likings, :friends, :mini_post_favorites, :blog_settings, :path_prefix => '/:locale'
  
  resources :phone_numbers, :only => [:new,:create]

  resources :charges

  resources :search do
    post 'go-to-category', :controller => 'search', :action => 'go_to_category', :method => :post
    get 'complete', :controller => 'search', :action => 'complete', :method => :get
    post 'find',:controller => 'search',:action=>'find',:method=>:post
  end
 
  resources :index do
    post 'addcoupon',:controller => 'index',:action => 'addcoupon',:method => :post
    post 'checknick',:controller => 'index',:action => 'checknick',:method => :post
    post 'checkemail',:controller =>'index',:action => 'checkemail',:method =>:post
  end

  resource :messages do

    post 'get',  :controller=>'messages', :action=>'read_message',  :method=>'get'
    post 'get',  :controller=>'messages', :action=>'reveal',  :method=>'get'
  end
  
  resource :options do
    post 'registrations_mode',  :controller=>'options', :action=>'registrations_mode',  :method=>'post'
  end

  resource :messages do
    post 'set-status',  :controller=>'statuses', :action=>'usestatus',  :method=>'post'
  end

  resource :users do
    post 'set-background',  :controller=>'users', :action=>'set_background',  :method=>'post'
  end

  resources :mini_posts do
    resources :mini_post_comments,:mini_post_tags,:mini_post_likings,:mini_post_comment_likings,:mini_post_feeds,:feeds
      get 'mini_posts',:controller => 'mini_posts',:action => 'index',:method => :get
      
      post 'like',:controller => 'mini_posts', :action => 'like', :method => :post
      post 'liked',:controller => 'mini_posts', :action => 'liked', :method => :post
      post 'liking',:controller => 'mini_posts', :action => 'liking', :method => :post
      post 'disliking',:controller => 'mini_posts', :action => 'disliking', :method => :post
      post 'favoriting',:controller => 'mini_posts', :action => 'favoriting', :method => :post
      post 'sharel',:controller => 'mini_posts', :action => 'sharel', :method => :post
      post 'sharep',:controller => 'mini_posts', :action => 'sharep', :method => :post
      post 'disklike',:controller => 'mini_posts',:action => 'dislike',:method => :post
  end
 
  resources :iposts, only: [:index, :show]
  get '/posts_with_button', to: 'iposts#index_with_button', as: 'posts_with_button'
  
  resources :wall do 
    resources :mini_post_comments,:mini_post_tags,:mini_post_likings,:mini_post_comment_likings
      get 'wall', :controller => 'wall', :action => 'index', :method => :get
      get 'likes', :controller => 'wall', :action => 'likes', :method => :get
      get 'favorites', :controller => 'wall', :action => 'favorites', :method => :get
      get 'updwall', :controller => 'wall', :action => 'indexupd', :method => :get
  end

  resources :posts do
      post 'save_settings', :controller => 'posts', :action => 'save_settings', :method => :post
      post 'idtag', :controller => 'posts', :action => 'idtag', :method => :post
  end

  resources :contacts do
    patch :crop, on: :member
  end
  
  resources :users do
    patch :crop, on: :member
	end

  resource :carts do
    post 'add-to-cart',  :controller=>'carts', :action=>'add_to_cart',  :method=>'post'
	end

  resource :orders do
    post 'express',  :controller=>'orders', :action=>'express',  :method=>'post'
    post 'confirm',  :controller=>'carts', :action=>'confirm',  :method=>'post'
    get 'notification', :controller =>'orders',:action=>'notification',:method=>'get'
    get 'success', :controller =>'orders',:action=>'success',:method=>'get'
    get 'failure', :controller =>'orders',:action=>'failure',:method=>'get'
  end

  resource :agadanga do
    post 'agadanga-send',  :controller=>'agadanga', :action=>'agadanga_send',  :method=>'post'
    post 'agadanga-save-draft', :controller=>'agadanga', :action=>'agadanga_save_draft', :method=>'post'
    post 'agadanga-discard', :controller=>'agadanga', :action=>'agadanga_discard', :method=>'post'
  end
  
  devise_scope :user do
    get 'register'         => 'devise/registrations#new' 
    get 'signup'           => 'devise/registrations#new' 
    get 'login'            => 'devise/sessions#new'    
    get 'signin'           => 'devise/sessions#new'    
    get 'logout'           => 'devise/sessions#destroy'
    get 'exit'             => 'devise/sessions#destroy'
    get 'refresh-password' => 'devise/registrations#edit' 
    get 'change-password'  => 'devise/registrations#edit'
    get 'activation'  => 'devise/registrations#activation'
    get 'coupon_activation'  => 'devise/registrations#coupon_activation'
  end
  
  authenticated :user do
    root to: 'users#home', as: :authenticated_root
  end

 # unauthenticated do
    root to: 'index#index'#, as: :unauthenticated_root
 # end
 
  namespace :api do
    namespace :v1 do
      resources :messages,:contacts,:statuses,:countries,:efiles,:statuses,:user_contacts,:invitations,:search,:uploads, :defaults => { :format => 'json' }
    end
  end

  resource :agadanga do
    post 'agadanga-send',  :controller=>'agadanga', :action=>'agadanga_send',  :method=>'post'
    post 'agadanga-save-draft', :controller=>'agadanga', :action=>'agadanga_save_draft', :method=>'post'
    post 'agadanga-discard', :controller=>'agadanga', :action=>'agadanga_discard', :method=>'post'
  end

  resource :pictures do
    post 'upload-picture',  :controller=>'pictures', :action=>'create',  :method=>'post'
  end

  resource :feedbacks do
    post 'send-feedback',  :controller=>'feedbacks', :action=>'create',  :method=>'post'
  end

  post 'registrations_mode' => 'options#registrations_mode'
  post 'addcontact'    => 'user_contacts#create'
  post 'usestatus'     => 'statuses#usestatus'
  post 'check_passphrase'   => 'messages#check_passphrase'

  post 'activation'    => 'charges#create'
  post 'coupon_activation'   => 'charges#create'

  post 'set-background'       => 'users#set_background'
  post 'set-status'           => 'statuses#usestatus'

  get 'hashtags/:hashtag',   to: 'hashtags#show',      as: :hashtag
  get 'hashtags',            to: 'hashtags#index',     as: :hashtags


  get 'revealed'       => 'messages#revealed'

  get 'likes'                => 'wall#likes'
  get 'favorites'            => 'wall#favorites'

  get 'store'                => 'products#store'
  get 'visitors'             => 'users#visitors'
  get 'links'                => 'links#index'
  get 'authors'              => 'authors#index'
  get 'quotes'               => 'quotes#index'
  get 'quote_types'          => 'quote_types#index'
  get 'ads'                  => 'ads#index'
  get 'feedbacks'            => 'feedbacks#index'

	post 'send-feedback'       => 'feedbacks#create'
  get 'products'             => 'products#index'
  get 'payments'             => 'payments#index'
	get 'orders'               => 'orders#index'
  get 'invoices'             => 'invoices#index'
  get 'store'                => 'products#store'

  post 'express-checkout'    => 'carts#express_checkout'
  get 'subscribe'            => 'carts#show'
  post 'express'             => 'orders#express'
  post 'update-cart'         => 'carts#update_cart'

  get 'contribution'   => 'charges#new'

  get 'tags'           => 'tags#index'
  get 'idtag'          => 'posts#idtag'

  get 'posts'          => 'posts#index'

  get 'taggings'       => 'posts#taggings'

  get 'notifications'  => 'updates#index'
  get 'updates'        => 'updates#{@i}index'
  get 'blocked'        => 'blocked_users#index'
  get 'banned'         => 'blocked_users#index'
  get 'invitations'    => 'invitations#index'
  get 'requests'       => 'requests#index'
  get 'gallery'        => 'pictures#index'
  get 'pictures'       => 'pictures#index'
  get 'images'         => 'pictures#index'
  get 'home'           => 'users#home'

  post 'upload-picture'=> 'pictures#create'


  get 'superlogin'     => 'index#superlogin'

  get 'blog'           => 'posts#blog'
  get 'blog-settings'  => 'posts#settings'
  #get 'blog2'          => 'posts#blog2'

  post 'savesettings'  => 'posts#savesettings'
  get 'd4x337'      => 'posts#d4x337'
  get 'blog-tags'      => 'tags#index'
  get 'blog-author'    => 'posts#d4x337'
  get 'tags-d4x337'    => 'posts#tags'
  get 'author-d4x337'  => 'posts#d4x337'
  post 'like'          => 'mini_posts#like'
  post 'liked'         => 'mini_posts#liked'
  post 'liking'        => 'mini_posts#liking'
  post 'disliking'     => 'mini_posts#disliking'
  post 'favoriting'    => 'mini_posts#favoriting'
  post 'sharel'        => 'wall#sharel'
  post 'sharep'        => 'wall#sharep'

  get 'timeline'       => 'timeline#index'
  get 'atimeline'      => 'timeline#admin'

  get 'wall'           => 'wall#index'
  get 'lounge'         => 'wall#index'
  get 'updwall'        => 'wall#indexupd'

  get 'requests'       => 'requests#index'
  get 'network'        => 'friends#index'
  get 'connections'    => 'friends#index'

app/models/mini_post_comment_liking.rb
class MiniPostCommentLiking < ActiveRecord::Base
    attr_accessible :user_id,:mini_post_comment_id,:liking,:created_at,:deleted
    belongs_to :user
    belongs_to :mini_post_comment
   
    validates :mini_post_comment_id, :presence => true
    validates :user_id, :presence => true

 #   include PublicActivity::Model
 #   tracked
end

app/controllers/mini_post_comment_likings_controller.rb
class MiniPostCommentLikingsController < ApplicationController
  
  before_filter :authenticate_user!
  layout :custom_layout

  
  def create
    @mini_post_comment_liking = MiniPostCommentLiking.new(params[:mini_post_comment_liking])
    @user = current_user
    @mini_post_comment_liking.user_id = @user.id;
   
    if params[:feed] == "like"
      @mini_post_comment_liking.liking = true
    elsif params[:feed] == "dislike"
      @mini_post_comment_liking.liking = false
    end  
     
    respond_to do |format|
      if @mini_post_comment_liking.save
        format.html  { redirect_to(request.referer,:notice => 'Feed added') }
        format.json  { render :json => @mini_post_comment_liking, :status => :created, :location => @mini_post_likings }
      else
        format.html  { redirect_to(request.referer)}
        format.json  { render :json => @mini_post_comment_liking.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @mini_post_comment_liking = MiniPostCommentLiking.find(params[:mini_post_comment_liking][:mini_post_comment_liking_id])
    @mini_post_comment_liking.destroy
     respond_to do |format|
       format.html  { redirect_to(request.referer,:notice => 'Feed deleted') }
       format.json { head :no_content }
    end
  end
  
  def index
    #@things = current_user.things
    @mini_post_comment_liking = MiniPostCommentLiking.all
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @mini_post_comment_liking }
    end
  end

  def show
    @mini_post_comment_liking = MiniPostCommentLiking.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @mini_post_comment_liking }
    end
  end

  def new
    @mini_post_comment_likings = MiniPostCommentLiking.new
    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @mini_post_comment_likings }
    end
  end

  def edit
    @mini_post_comment_likings = MiniPostCommentLiking.find(params[:id])
  end

    
  def update
    @mini_post_comment_likings = MiniPostCommentLiking.find(params[:id])
     if params[:like] == "like"
      @mini_post_comment_likings.liking = true
    elsif params[:dislike] == "dislike"
      @mini_post_comment_likings.liking = false
    end  
  
    respond_to do |format|
      if @mini_post_comment_likings.update_attributes(params[:mini_post_comment_liking])
         format.html  { redirect_to(request.referer,:notice => 'Feed updated') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @mini_post_comment_likings.errors,:status => :unprocessable_entity }
      end
    end
  end

 
  private
  def custom_layout
       if current_user.role? :admin  
        "dashboard"    
       else current_user.role? :user
        "welcome"
       end 
   end
end

app/views/mini_post_comment_likings/_form.html.erb
<%= form_for(@mini_post_comment_likings) do |f| %>
  <% if @mini_post_comment_likings.errors.any? %>
    <div  id="login-messages" class="ui-widget">
		<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
			<p align="center"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
			<strong class="error-counter"><%= pluralize(@mini_post_comment_likings.errors.count, t("error")) %> :</strong> </p>
			 <div id="error-list">
				 <% @mini_post_comment_likings.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      <br />
		      </div>
		</div>
	</div>
	<br />
  <% end %>

   <div class="field">
    <%= f.label t(:user) %><% current_user.id %><br />
    <%= f.text_field :user_id %>
  </div><br>
  <div class="field">
    <%= f.label t(:mini_post_comment_id) %><br />
    <%= f.text_field :mini_post_comment_id %>
  </div><br>
  <div class="field">
    <%= f.label t(:liking) %><br />
   
  </div><br>
  <div class="field">
    <%= f.label t(:liking) %><br />
    <%= f.submit "like" ,:name=>"like",:type=>:image,:src => "/images/like.png" %>
    <%= f.submit "dislike",:name=>"dislike",:type=>:image,:src => "/images/dislike.png" %>
   </div><br>
   <div class="field">
    <%= f.label t(:created_at) %><br />
    <%= f.text_field :created_at %>
  </div>
  <br>
<% end %>

app/views/mini_post_comment_likings/edit.html.erb
<div id="text-content">
	<p id="notice">
		<%= notice %>
	</p>
	<h2><%= t('Update feed') %></h2>

<%= render 'form' %>

<%= link_to t('Show'), @mini_post_comment_liking %> |
<%= link_to t('Back'), mini_post_comment_likings_path %>
</div>

app/views/mini_post_comment_likings/index.html.erb
<div id="text-content">
			<h3><%= t('listing mini_post_comment_likings') %></h3>
			<p id="notice">
				<%= notice %>
			</p>
		<%= link_to t('new mini_post_comment_liking'), new_mini_post_comment_liking_path %>
		<br><br>
		<table width="100%">
		  <tr>
		  	<th align="left" width="5%" ><%=t(:id) %></th>
		    <th align="left" width="15%" ><%=t(:mini_post_id) %></th>
		    <th align="left" width="20%" ><%=t(:user_id) %></th>
		    <th align="left" width="25%" ><%=t(:created_at) %></th>
		    <th align="left" width="10%" ><%=t(:linking) %></th>
		    <th align="left" width="10%" ><%=t(:deleted) %></th>
		  </tr>
		 <% @mini_post_comment_liking.each do |mini_post_comment_liking| %>
		  <tr>
		  	<td><%= mini_post_comment_liking.id %></td>
		    <td><%= mini_post_comment_liking.mini_post_comment_id %></td>
		    <td><%= mini_post_comment_liking.user_id %></td>
		    <td><%= mini_post_comment_liking.created_at %></td>
		    <td><%= mini_post_comment_liking.liking %></td>
		 	<td><%= mini_post_comment_liking.deleted %></td>
		 	<td>
		 		<%= link_to image_tag("icon-list-new.gif", :border =>0, :mouseover => "icon-list-new-over.gif", :title => t("icon-show") ,:size => "16x16"), mini_post_comment_liking %>
		 	</td>
			<td>
				<% if can? :update, @mini_post_comment_liking %>  
					<%= link_to image_tag("icon-list-update.gif", :border =>0, :mouseover => "icon-list-update-over.gif", :title => t("icon-edit"),:size => "16x16" ), edit_mini_post_comment_liking_path(mini_post_comment_liking) %>
				<% end %>
			</td>
		    <td>
			
					<%= button_to "", mini_post_comment_liking, :confirm => 'Are you sure?', :method => :delete ,:size => "20x20"%>
				
			</td>
		  </tr>
		<% end %>
		</table>
</div>

app/views/mini_post_comment_likings/new.html.erb
<div id="text-content">
	<h2><%= t('New feed - Cool or..Lame') %></h2>
	<br />
	<%= render 'form' %>
	<%= link_to t('Back'), mini_post_comment_likings_path %>
</div>

app/views/mini_post_comment_likings/show.html.erb
<div id="mini_post_comment_liking-evo" onmouseover="style.border='2px #00FF00 solid';"  onmouseout="style.border='2px #004B00 solid';">
	<div id="mini_post_comment_liking-evo-title">
		<div id="evo-card-icon">
			<%= image_tag "card-icon-mini_post_comment_likings.gif",:size => "24x24",:alt => "cool mini_post_comment_liking!" %> 						
		</div>
		<div id="mini_post_comment_liking-card-title">
			<%= @mini_post_comment_liking.liking %>					
		</div>
		<div id="evo-card-actions">
		</div>
	</div>
	<br>
		<table id="single-mini_post_comment_liking">
			<tr>
				<td width="30"></td>
				<td width="50"></td>
				<td width="30"></td>
				<td></td>
				<td rowspan="9" align="center">
					<div id="snapshot-mini_post_comment_liking">
					
					</div>
				 	<% if can? :update, @mini_post_comment_liking %>  
						| <%= link_to t('edit this entry'), edit_mini_post_comment_liking_path(@mini_post_comment_liking) %> | 
						<%= link_to t('back to mini_post_comment_likings list'), mini_post_comment_likings_path %> |
					<% end %>
				</td>
			</tr>
			<tr>
				<td colspan="4" width="320" class="d4x-title1"><%= @mini_post_comment_liking.user_id %></td>
				<td></td>
			</tr>
			<tr>
				
				<td colspan="4" width="65%" class="d4x-title2"><%= @mini_post_comment_liking.mini_post_comment_id %></td>
				<td></td>
			</tr>
			<tr>
				<td colspan="4" width="65%" class="d4x-title3"><div id="summary-content"><%= @mini_post_comment_liking.created_at %></div></td>
				<td></td>
			</tr>
			<tr>
				<td colspan="4" width="320" class="d4x-title3"></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		</table>
	<br>
</div><!--NEW CARD1 -->