config/routes.rb
Reloaded::Application.routes.draw do

  use_doorkeeper

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  #devise_for :users, :controllers => { :registrations => "users/registrations",:sessions => "users/sessions" }
  
 #  devise_for :users, :controllers => { :registrations => "users/registrations", 
 #   :sessions=> 'users/sessions',:invitations => 'users/invitations', 
 #   :omniauth_callbacks=>'omniauth_callbacks' },
 #   :token_authentication_key => 'authentication_key'3333333333333333333333333

  resources :user_contacts, :users, :statuses, :efiles, :search, :contacts, :options, :invitations, :chats, :blocked_users, :channels, :channel_users, :shadow,
            :messages,:products,:carts,:cart_items,:ads,:orders,:feedbacks,:cart_products,:quotes,:quote_types,:authors,:links, :uploads, :countries, :posts,:domains,:mail_accounts,:pictures,:alias_maps,:mini_post_comments, :timeline, :mini_post_comment_likings,:tags, :updates, :post_tags, :requests, :mini_post_likings, :friends, :mini_post_favorites, :blog_settings, :path_prefix => '/:locale'
  
  resources :phone_numbers, :only => [:new,:create]

  resources :charges

  resources :search do
    post 'go-to-category', :controller => 'search', :action => 'go_to_category', :method => :post
    get 'complete', :controller => 'search', :action => 'complete', :method => :get
    post 'find',:controller => 'search',:action=>'find',:method=>:post
  end
 
  resources :index do
    post 'addcoupon',:controller => 'index',:action => 'addcoupon',:method => :post
    post 'checknick',:controller => 'index',:action => 'checknick',:method => :post
    post 'checkemail',:controller =>'index',:action => 'checkemail',:method =>:post
  end

  resource :messages do

    post 'get',  :controller=>'messages', :action=>'read_message',  :method=>'get'
    post 'get',  :controller=>'messages', :action=>'reveal',  :method=>'get'
  end
  
  resource :options do
    post 'registrations_mode',  :controller=>'options', :action=>'registrations_mode',  :method=>'post'
  end

  resource :messages do
    post 'set-status',  :controller=>'statuses', :action=>'usestatus',  :method=>'post'
  end

  resource :users do
    post 'set-background',  :controller=>'users', :action=>'set_background',  :method=>'post'
  end

  resources :mini_posts do
    resources :mini_post_comments,:mini_post_tags,:mini_post_likings,:mini_post_comment_likings,:mini_post_feeds,:feeds
      get 'mini_posts',:controller => 'mini_posts',:action => 'index',:method => :get
      
      post 'like',:controller => 'mini_posts', :action => 'like', :method => :post
      post 'liked',:controller => 'mini_posts', :action => 'liked', :method => :post
      post 'liking',:controller => 'mini_posts', :action => 'liking', :method => :post
      post 'disliking',:controller => 'mini_posts', :action => 'disliking', :method => :post
      post 'favoriting',:controller => 'mini_posts', :action => 'favoriting', :method => :post
      post 'sharel',:controller => 'mini_posts', :action => 'sharel', :method => :post
      post 'sharep',:controller => 'mini_posts', :action => 'sharep', :method => :post
      post 'disklike',:controller => 'mini_posts',:action => 'dislike',:method => :post
  end
 
  resources :iposts, only: [:index, :show]
  get '/posts_with_button', to: 'iposts#index_with_button', as: 'posts_with_button'
  
  resources :wall do 
    resources :mini_post_comments,:mini_post_tags,:mini_post_likings,:mini_post_comment_likings
      get 'wall', :controller => 'wall', :action => 'index', :method => :get
      get 'likes', :controller => 'wall', :action => 'likes', :method => :get
      get 'favorites', :controller => 'wall', :action => 'favorites', :method => :get
      get 'updwall', :controller => 'wall', :action => 'indexupd', :method => :get
  end

  resources :posts do
      post 'save_settings', :controller => 'posts', :action => 'save_settings', :method => :post
      post 'idtag', :controller => 'posts', :action => 'idtag', :method => :post
  end

  resources :contacts do
    patch :crop, on: :member
  end
  
  resources :users do
    patch :crop, on: :member
	end

  resource :carts do
    post 'add-to-cart',  :controller=>'carts', :action=>'add_to_cart',  :method=>'post'
	end

  resource :orders do
    post 'express',  :controller=>'orders', :action=>'express',  :method=>'post'
    post 'confirm',  :controller=>'carts', :action=>'confirm',  :method=>'post'
    get 'notification', :controller =>'orders',:action=>'notification',:method=>'get'
    get 'success', :controller =>'orders',:action=>'success',:method=>'get'
    get 'failure', :controller =>'orders',:action=>'failure',:method=>'get'
  end

  resource :agadanga do
    post 'agadanga-send',  :controller=>'agadanga', :action=>'agadanga_send',  :method=>'post'
    post 'agadanga-save-draft', :controller=>'agadanga', :action=>'agadanga_save_draft', :method=>'post'
    post 'agadanga-discard', :controller=>'agadanga', :action=>'agadanga_discard', :method=>'post'
  end
  
  devise_scope :user do
    get 'register'         => 'devise/registrations#new' 
    get 'signup'           => 'devise/registrations#new' 
    get 'login'            => 'devise/sessions#new'    
    get 'signin'           => 'devise/sessions#new'    
    get 'logout'           => 'devise/sessions#destroy'
    get 'exit'             => 'devise/sessions#destroy'
    get 'refresh-password' => 'devise/registrations#edit' 
    get 'change-password'  => 'devise/registrations#edit'
    get 'activation'  => 'devise/registrations#activation'
    get 'coupon_activation'  => 'devise/registrations#coupon_activation'
  end
  
  authenticated :user do
    root to: 'users#home', as: :authenticated_root
  end

 # unauthenticated do
    root to: 'index#index'#, as: :unauthenticated_root
 # end
 
  namespace :api do
    namespace :v1 do
      resources :messages,:contacts,:statuses,:countries,:efiles,:statuses,:user_contacts,:invitations,:search,:uploads, :defaults => { :format => 'json' }
    end
  end

  resource :agadanga do
    post 'agadanga-send',  :controller=>'agadanga', :action=>'agadanga_send',  :method=>'post'
    post 'agadanga-save-draft', :controller=>'agadanga', :action=>'agadanga_save_draft', :method=>'post'
    post 'agadanga-discard', :controller=>'agadanga', :action=>'agadanga_discard', :method=>'post'
  end

  resource :pictures do
    post 'upload-picture',  :controller=>'pictures', :action=>'create',  :method=>'post'
  end

  resource :feedbacks do
    post 'send-feedback',  :controller=>'feedbacks', :action=>'create',  :method=>'post'
  end

  post 'registrations_mode' => 'options#registrations_mode'
  post 'addcontact'    => 'user_contacts#create'
  post 'usestatus'     => 'statuses#usestatus'
  post 'check_passphrase'   => 'messages#check_passphrase'

  post 'activation'    => 'charges#create'
  post 'coupon_activation'   => 'charges#create'

  post 'set-background'       => 'users#set_background'
  post 'set-status'           => 'statuses#usestatus'

  get 'hashtags/:hashtag',   to: 'hashtags#show',      as: :hashtag
  get 'hashtags',            to: 'hashtags#index',     as: :hashtags


  get 'revealed'       => 'messages#revealed'

  get 'likes'                => 'wall#likes'
  get 'favorites'            => 'wall#favorites'

  get 'store'                => 'products#store'
  get 'visitors'             => 'users#visitors'
  get 'links'                => 'links#index'
  get 'authors'              => 'authors#index'
  get 'quotes'               => 'quotes#index'
  get 'quote_types'          => 'quote_types#index'
  get 'ads'                  => 'ads#index'
  get 'feedbacks'            => 'feedbacks#index'

	post 'send-feedback'       => 'feedbacks#create'
  get 'products'             => 'products#index'
  get 'payments'             => 'payments#index'
	get 'orders'               => 'orders#index'
  get 'invoices'             => 'invoices#index'
  get 'store'                => 'products#store'

  post 'express-checkout'    => 'carts#express_checkout'
  get 'subscribe'            => 'carts#show'
  post 'express'             => 'orders#express'
  post 'update-cart'         => 'carts#update_cart'

  get 'contribution'   => 'charges#new'

  get 'tags'           => 'tags#index'
  get 'idtag'          => 'posts#idtag'

  get 'posts'          => 'posts#index'

  get 'taggings'       => 'posts#taggings'

  get 'notifications'  => 'updates#index'
  get 'updates'        => 'updates#{@i}index'
  get 'blocked'        => 'blocked_users#index'
  get 'banned'         => 'blocked_users#index'
  get 'invitations'    => 'invitations#index'
  get 'requests'       => 'requests#index'
  get 'gallery'        => 'pictures#index'
  get 'pictures'       => 'pictures#index'
  get 'images'         => 'pictures#index'
  get 'home'           => 'users#home'

  post 'upload-picture'=> 'pictures#create'


  get 'superlogin'     => 'index#superlogin'

  get 'blog'           => 'posts#blog'
  get 'blog-settings'  => 'posts#settings'
  #get 'blog2'          => 'posts#blog2'

  post 'savesettings'  => 'posts#savesettings'
  get 'd4x337'      => 'posts#d4x337'
  get 'blog-tags'      => 'tags#index'
  get 'blog-author'    => 'posts#d4x337'
  get 'tags-d4x337'    => 'posts#tags'
  get 'author-d4x337'  => 'posts#d4x337'
  post 'like'          => 'mini_posts#like'
  post 'liked'         => 'mini_posts#liked'
  post 'liking'        => 'mini_posts#liking'
  post 'disliking'     => 'mini_posts#disliking'
  post 'favoriting'    => 'mini_posts#favoriting'
  post 'sharel'        => 'wall#sharel'
  post 'sharep'        => 'wall#sharep'

  get 'timeline'       => 'timeline#index'
  get 'atimeline'      => 'timeline#admin'

  get 'wall'           => 'wall#index'
  get 'lounge'         => 'wall#index'
  get 'updwall'        => 'wall#indexupd'

  get 'requests'       => 'requests#index'
  get 'network'        => 'friends#index'
  get 'connections'    => 'friends#index'

app/models/update.rb
class Update < ActiveRecord::Base

#  belongs_to :user,:class_name=>'User', :foreign_key => :user_id
  
  attr_accessible :sender_id,:target_id,:read,:reason,:created_at,:read_at,:message
    # attr_accessible :title, :body
  has_one :sender, :class_name=>'User', :foreign_key => :sender_id
  has_one :destination, :as => :user, :foreign_key => :target_id
  validates :sender_id,:target_id, :presence => true
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController

  load_and_authorize_resource
  before_filter :authenticate_user!
  layout "social"

  def index
     @count_new = Update.where(:target_id => current_user.id,:read => false).count
     @updates   = Update.where(:target_id => current_user.id).order(:read)
     @nowread   = Update.where(:target_id => current_user.id,:read => false)
     @nowread.each do |update|
       update.read = true
       update.save!
     end
     respond_to do |format|
      format.js
      format.html # index.html.erb
      format.json  { render :json => @updates }
    end
  end
  
  def admin
     #@things = current_user.things
     @updates = Update.all
     respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @updates }
    end
  end
  
  def show
    @update = Update.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @update }
    end
  end

  def new
    @update = Update.new
    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @updates }
    end
  end

  def edit
    @update = Update.find(params[:id])
  end

  def create
    @update = Update.new(params[:update])
      respond_to do |format|
      if @update.save
        format.html  { redirect_to(request.referer,
                  :notice => 'update successfully created') }
        format.json  { render :json => @update, :status => :created, :location => @update }
 
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @update.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
     @update = Update.find(params[:id])
     
     #@update.read = params['update_read']
     if params['update_read']= '0'
       @update.read = true
      else
        @update.read = false
      end
      @update.read_at = DateTime.now
     respond_to do |format|
      if @update.update_attributes(params[:update])
        format.html  { redirect_to(request.referer, :notice =>  'notification has been read ') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @update.errors, :status => :unprocessable_entity }
      end
    end
  end

  def updateOLD
    @update = Update.find(params[:id])
    
    if not params[:update_read].blank?
      if params[:update_read] = '1'
       @update.read = true
      elsif  params[:update_read] = '0'
        @update.read = false
      end
      respond_to do |format|
        if @update.update_attributes(params[:update])
          format.html  { redirect_to(request.referer, :notice =>  'Updates has been read') }
          format.json  { head :no_content }
        else
          format.html  { redirect_to(request.referer, :notice =>  'update what?') }
          format.json  { head :no_content }
        end
      end
    end
  end

  def destroy
  @update = Update.find(params[:id])
  @update.destroy
    respond_to do |format|
       format.html { redirect_to request.referer }
       format.json { head :no_content }
    end
  end
  
  private
  def custom_layout
       if current_user.role? :admin  
        "dashboard"    
       else current_user.role? :user
        "welcome"
       end 
   end

end

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div  id="login-messages" class="ui-widget">
		<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
			<p align="center"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
			<strong class="error-counter"><%= pluralize(@update.errors.count, t("error")) %> :</strong> </p>
			 <div id="error-list">
				 <% @update.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      <br />
		      </div>
		</div>
	</div>
	<br />
  <% end %>
 <div class="field">
    <%= f.label t(:sender) %><br />
    <%= f.text_field :sender_id %>
  </div><br>
  <div class="field">
    <%= f.label t(:destination) %><br />
    <%= f.text_field :target_id %>
  </div><br>
  <div class="field">
    <%= f.label t(:reason) %><br />
    <%= f.text_field :reason %>
  </div><br>
  <div class="field">
    <%= f.label t(:message) %><br />
    <%= f.text_field :message %>
  </div><br>
  <div class="field">
    <%= f.label t(:read) %><br />
    <%= f.text_field :read %>
  </div><br>
  <div class="field">
    <%= f.label t(:created) %><br />
    <%= f.text_field :created_at %>
  </div><br>
 
  <div class="actions">
   <%= f.submit :class=>'button-d4x' %>
  </div>
  <br>
<% end %>

app/views/updates/admin.html.erb
<% @title =t('admin updates') %>
<div id="big-card">
	<div id="big-card-title">
		
		<div id="evo-card-icon">
			<% if can? :update, @update %>  
				<%= link_to image_tag("bell.png", :border =>0, :mouseover => "bell.png", :title => t("icon-updates") ), new_update_path %>
			<% end %>
		</div>
		<div id="d4x-title-evo">
			<%= t('updates') %>	
		</div>
	</div>
	<table width="100%" class="d4x-grid">
		  <tr>
		  	<th align="left" width="5%" ><%=t(:id) %></th>
		    <th align="left" width="30%" ><%=t(:title) %></th>
		    <th align="left" width="15%" ><%=t(:published) %></th>
		    <th align="left" width="15%" ><%=t(:severity) %></th>
		    <th align="left" width="15%" ><%=t(:cve) %></th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		 <% @updates.each do |update| %>
		    <tr class="<%= cycle("odd","even")%> d4x-row-grid">
		  	<td><%= update.id %></td>
		    <td><%= update.title %></td>
		    <td><%= update.published %></td>
		    <td><%= update.severity %></td>
		    <td><%= update.cve %></td>
		    
		      <td>
				<%= link_to image_tag("bell.png", :border =>0 , :mouseover => "bell.png", :title => t("icon-show") ,:size => "16x16"), update %>
		 	</td>
			<td>
				<% if can? :update, @update %>  
					<%= link_to image_tag("edit.png", :border =>0, :mouseover => "update.gif", :title => t("icon-edit"),:size => "16x16" ), edit_update_path(update) %>
				<% end %>
			</td>
		    <td>
		    	<% if can? :destroy, @update %>  
						<%= button_to "", update, :confirm => 'are you sure?', :method => :delete, :class => 'destroy',:name => 'destroy',:size => "16x16" %>
				<% end %>
			</td>
		    	  </tr>
		<% end %>
		</table>
	</div>

app/views/updates/edit.html.erb
<% @title =t('Editing update') %>
<div id="center-right-welcome">
	<div id="text-content">
		<p id="notice">
			<%= notice %>
		</p>
		<h2><%= t('Editing update') %></h2>
		
		<%= render 'form' %>
		
		<%= link_to t('Show'), @update %> |
		<%= link_to t('Back'), updates_path %>
	</div>
</div>

app/views/updates/index.html.erb
<script language="JavaScript">
    $( document ).ready(function() {
        $('#main-menu-social').addClass("navigation__sub--active navigation__sub--toggled");
        $('#menu-notifications                                                  ').removeClass("navigation__sub").addClass("navigation__active");
    });
</script>
<h4 class="card-title bluesocial"><i class="zmdi zmdi-notifications bluesocial"></i>   <%= label_tag(t("notifications"),nil,:class=>'' )%> <%= "@"+current_user.nickname %></h4>      &nbsp;
<% if @count_new > 0 %><%= t("you have") %>&nbsp;<%= @count_new.to_s %>&nbsp;<%= d4x_sanitizer(t("pending notifications")) %><% end %>

<% unless @updates.blank? %>
  <div class="listview listview--hover">
  <% @updates.each do |update| %>
    <% @xuser = User.find(update.sender_id) %>
        <a href="" class="listview__item traspa">

          <% if @xuser.avatar(:thumb).present? %>
              <img class="listview__img" src="<%= @xuser.avatar.url(:thumb) %>" alt="">
          <% else %>
              <img class="listview__img" src="/assets/demo/img/profile-pics/1.jpg" alt="">
          <% end %>

          <div class="listview__content">
            <div class="listview__heading">
              <%= label_tag "@"+user_nick(@xuser.id),nil,{:class=>'orange'} %>&nbsp;
              <small class="pull-right">
                <%= time_ago_in_words_converter(update.created_at) %>&nbsp;<%= t('ago') %>
                <%= button_to update,:class=>"btn btn-sm btn-outline-warning",:method => :delete,:title=>t('cancel invitation'),:confirm => t('Are you sure you want to cancel this invitation?') do %>
                    <%= t('read') %>
                <% end %>
              </small>
              <br>
              <%= update.reason %>
            </div>
          </div>
        </a>

  <% end %>
  </div>
<% else %>
  <%= t('you do not have any new notification') %>
  <br>
<% end %>

app/views/updates/new.html.erb
<% @title =t('New update') %>
<div id="center-right-welcome">
	<div id="text-content">
		<% if can? :update, @update %>  
			<h2><%= t('New update') %></h2>
		<% end %>
		<br />
		<%= render 'form' %>
		<%= link_to t('Back'), updates_path %>
	</div>
</div>

app/views/updates/show.html.erb
<% @title =t('update') %>
<div id="link-evo">
	<div id="show-title">
		<div id="evo-card-icon">
			<%= image_tag "card-icon-vulns.gif",:size => "24x24",:alt => "notification" %> 						
		</div>
		<div id="link-card-title">
			 <%= @update.sender_id %>	
		</div>
		<div id="evo-card-actions">
			
		</div>
	</div>
	<div id="show-body">
		
	
			<% if (@update.reason != nil) %>
				
				<div id="show-item">
					<div id="show-item-left">
						<%= t('reason') %>
					</div>
					<div id="show-item-right">
						<%= @update.reason %>
					</div>
				</div>
				<br>
				
			<% end %>
			
		</div>
	 	<% if can? :update, @update %>  
			 <%= link_to t('edit'), edit_update_path(@update) %> 
		<% end %>
	</div>

</div><!--NEW CARD1 -->