config/routes.rb
Reloaded::Application.routes.draw do

  use_doorkeeper

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  #devise_for :users, :controllers => { :registrations => "users/registrations",:sessions => "users/sessions" }
  
 #  devise_for :users, :controllers => { :registrations => "users/registrations", 
 #   :sessions=> 'users/sessions',:invitations => 'users/invitations', 
 #   :omniauth_callbacks=>'omniauth_callbacks' },
 #   :token_authentication_key => 'authentication_key'3333333333333333333333333

  resources :user_contacts, :users, :statuses, :efiles, :search, :contacts, :options, :invitations, :chats, :blocked_users, :channels, :channel_users, :shadow,
            :messages,:products,:carts,:cart_items,:ads,:orders,:feedbacks,:cart_products,:quotes,:quote_types,:authors,:links, :uploads, :countries, :posts,:domains,:mail_accounts,:pictures,:alias_maps,:mini_post_comments, :timeline, :mini_post_comment_likings,:tags, :updates, :post_tags, :requests, :mini_post_likings, :friends, :mini_post_favorites, :blog_settings, :path_prefix => '/:locale'
  
  resources :phone_numbers, :only => [:new,:create]

  resources :charges

  resources :search do
    post 'go-to-category', :controller => 'search', :action => 'go_to_category', :method => :post
    get 'complete', :controller => 'search', :action => 'complete', :method => :get
    post 'find',:controller => 'search',:action=>'find',:method=>:post
  end
 
  resources :index do
    post 'addcoupon',:controller => 'index',:action => 'addcoupon',:method => :post
    post 'checknick',:controller => 'index',:action => 'checknick',:method => :post
    post 'checkemail',:controller =>'index',:action => 'checkemail',:method =>:post
  end

  resource :messages do

    post 'get',  :controller=>'messages', :action=>'read_message',  :method=>'get'
    post 'get',  :controller=>'messages', :action=>'reveal',  :method=>'get'
  end
  
  resource :options do
    post 'registrations_mode',  :controller=>'options', :action=>'registrations_mode',  :method=>'post'
  end

  resource :messages do
    post 'set-status',  :controller=>'statuses', :action=>'usestatus',  :method=>'post'
  end

  resource :users do
    post 'set-background',  :controller=>'users', :action=>'set_background',  :method=>'post'
  end

  resources :mini_posts do
    resources :mini_post_comments,:mini_post_tags,:mini_post_likings,:mini_post_comment_likings,:mini_post_feeds,:feeds
      get 'mini_posts',:controller => 'mini_posts',:action => 'index',:method => :get
      
      post 'like',:controller => 'mini_posts', :action => 'like', :method => :post
      post 'liked',:controller => 'mini_posts', :action => 'liked', :method => :post
      post 'liking',:controller => 'mini_posts', :action => 'liking', :method => :post
      post 'disliking',:controller => 'mini_posts', :action => 'disliking', :method => :post
      post 'favoriting',:controller => 'mini_posts', :action => 'favoriting', :method => :post
      post 'sharel',:controller => 'mini_posts', :action => 'sharel', :method => :post
      post 'sharep',:controller => 'mini_posts', :action => 'sharep', :method => :post
      post 'disklike',:controller => 'mini_posts',:action => 'dislike',:method => :post
  end
 
  resources :iposts, only: [:index, :show]
  get '/posts_with_button', to: 'iposts#index_with_button', as: 'posts_with_button'
  
  resources :wall do 
    resources :mini_post_comments,:mini_post_tags,:mini_post_likings,:mini_post_comment_likings
      get 'wall', :controller => 'wall', :action => 'index', :method => :get
      get 'likes', :controller => 'wall', :action => 'likes', :method => :get
      get 'favorites', :controller => 'wall', :action => 'favorites', :method => :get
      get 'updwall', :controller => 'wall', :action => 'indexupd', :method => :get
  end

  resources :posts do
      post 'save_settings', :controller => 'posts', :action => 'save_settings', :method => :post
      post 'idtag', :controller => 'posts', :action => 'idtag', :method => :post
  end

  resources :contacts do
    patch :crop, on: :member
  end
  
  resources :users do
    patch :crop, on: :member
	end

  resource :carts do
    post 'add-to-cart',  :controller=>'carts', :action=>'add_to_cart',  :method=>'post'
	end

  resource :orders do
    post 'express',  :controller=>'orders', :action=>'express',  :method=>'post'
    post 'confirm',  :controller=>'carts', :action=>'confirm',  :method=>'post'
    get 'notification', :controller =>'orders',:action=>'notification',:method=>'get'
    get 'success', :controller =>'orders',:action=>'success',:method=>'get'
    get 'failure', :controller =>'orders',:action=>'failure',:method=>'get'
  end

  resource :agadanga do
    post 'agadanga-send',  :controller=>'agadanga', :action=>'agadanga_send',  :method=>'post'
    post 'agadanga-save-draft', :controller=>'agadanga', :action=>'agadanga_save_draft', :method=>'post'
    post 'agadanga-discard', :controller=>'agadanga', :action=>'agadanga_discard', :method=>'post'
  end
  
  devise_scope :user do
    get 'register'         => 'devise/registrations#new' 
    get 'signup'           => 'devise/registrations#new' 
    get 'login'            => 'devise/sessions#new'    
    get 'signin'           => 'devise/sessions#new'    
    get 'logout'           => 'devise/sessions#destroy'
    get 'exit'             => 'devise/sessions#destroy'
    get 'refresh-password' => 'devise/registrations#edit' 
    get 'change-password'  => 'devise/registrations#edit'
    get 'activation'  => 'devise/registrations#activation'
    get 'coupon_activation'  => 'devise/registrations#coupon_activation'
  end
  
  authenticated :user do
    root to: 'users#home', as: :authenticated_root
  end

 # unauthenticated do
    root to: 'index#index'#, as: :unauthenticated_root
 # end
 
  namespace :api do
    namespace :v1 do
      resources :messages,:contacts,:statuses,:countries,:efiles,:statuses,:user_contacts,:invitations,:search,:uploads, :defaults => { :format => 'json' }
    end
  end

  resource :agadanga do
    post 'agadanga-send',  :controller=>'agadanga', :action=>'agadanga_send',  :method=>'post'
    post 'agadanga-save-draft', :controller=>'agadanga', :action=>'agadanga_save_draft', :method=>'post'
    post 'agadanga-discard', :controller=>'agadanga', :action=>'agadanga_discard', :method=>'post'
  end

  resource :pictures do
    post 'upload-picture',  :controller=>'pictures', :action=>'create',  :method=>'post'
  end

  resource :feedbacks do
    post 'send-feedback',  :controller=>'feedbacks', :action=>'create',  :method=>'post'
  end

  post 'registrations_mode' => 'options#registrations_mode'
  post 'addcontact'    => 'user_contacts#create'
  post 'usestatus'     => 'statuses#usestatus'
  post 'check_passphrase'   => 'messages#check_passphrase'

  post 'activation'    => 'charges#create'
  post 'coupon_activation'   => 'charges#create'

  post 'set-background'       => 'users#set_background'
  post 'set-status'           => 'statuses#usestatus'

  get 'hashtags/:hashtag',   to: 'hashtags#show',      as: :hashtag
  get 'hashtags',            to: 'hashtags#index',     as: :hashtags


  get 'revealed'       => 'messages#revealed'

  get 'likes'                => 'wall#likes'
  get 'favorites'            => 'wall#favorites'

  get 'store'                => 'products#store'
  get 'visitors'             => 'users#visitors'
  get 'links'                => 'links#index'
  get 'authors'              => 'authors#index'
  get 'quotes'               => 'quotes#index'
  get 'quote_types'          => 'quote_types#index'
  get 'ads'                  => 'ads#index'
  get 'feedbacks'            => 'feedbacks#index'

	post 'send-feedback'       => 'feedbacks#create'
  get 'products'             => 'products#index'
  get 'payments'             => 'payments#index'
	get 'orders'               => 'orders#index'
  get 'invoices'             => 'invoices#index'
  get 'store'                => 'products#store'

  post 'express-checkout'    => 'carts#express_checkout'
  get 'subscribe'            => 'carts#show'
  post 'express'             => 'orders#express'
  post 'update-cart'         => 'carts#update_cart'

  get 'contribution'   => 'charges#new'

  get 'tags'           => 'tags#index'
  get 'idtag'          => 'posts#idtag'

  get 'posts'          => 'posts#index'

  get 'taggings'       => 'posts#taggings'

  get 'notifications'  => 'updates#index'
  get 'updates'        => 'updates#{@i}index'
  get 'blocked'        => 'blocked_users#index'
  get 'banned'         => 'blocked_users#index'
  get 'invitations'    => 'invitations#index'
  get 'requests'       => 'requests#index'
  get 'gallery'        => 'pictures#index'
  get 'pictures'       => 'pictures#index'
  get 'images'         => 'pictures#index'
  get 'home'           => 'users#home'

  post 'upload-picture'=> 'pictures#create'


  get 'superlogin'     => 'index#superlogin'

  get 'blog'           => 'posts#blog'
  get 'blog-settings'  => 'posts#settings'
  #get 'blog2'          => 'posts#blog2'

  post 'savesettings'  => 'posts#savesettings'
  get 'd4x337'      => 'posts#d4x337'
  get 'blog-tags'      => 'tags#index'
  get 'blog-author'    => 'posts#d4x337'
  get 'tags-d4x337'    => 'posts#tags'
  get 'author-d4x337'  => 'posts#d4x337'
  post 'like'          => 'mini_posts#like'
  post 'liked'         => 'mini_posts#liked'
  post 'liking'        => 'mini_posts#liking'
  post 'disliking'     => 'mini_posts#disliking'
  post 'favoriting'    => 'mini_posts#favoriting'
  post 'sharel'        => 'wall#sharel'
  post 'sharep'        => 'wall#sharep'

  get 'timeline'       => 'timeline#index'
  get 'atimeline'      => 'timeline#admin'

  get 'wall'           => 'wall#index'
  get 'lounge'         => 'wall#index'
  get 'updwall'        => 'wall#indexupd'

  get 'requests'       => 'requests#index'
  get 'network'        => 'friends#index'
  get 'connections'    => 'friends#index'

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  has_many :tag, :foreign_key => :id
  has_many :post,:foreign_key => :post_id
  validates :post_id, :tag_id, :presence => true
  attr_accessible :post_id, :tag_id
end

app/controllers/post_tags_controller.rb
class PostTagsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:home]
  load_and_authorize_resource
  
  
  def index
    #@things = current_user.things
    @post_tags = PostTag.all
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @post_tags }
    end
  end



  def show
    @post_tags = PostTag.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @post_tags }
    end
  end

  def new
    @post_tags = PostTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @post_tags }
    end
  end

  def edit
    @post_tags = PostTag.find(params[:id])
  end

  def create
    @post_tags = PostTag.new(post_tags_params)
    
  
    respond_to do |format|
      if @post_tags.save
        format.html  { redirect_to(post_tags_url,
                      :notice => 'Post-Tag was successfully created.') }
        format.json  { render :json => @post_tags,
                      :status => :created, :location => @post_tags }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @post_tags.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @post_tags = PostTag.find(params[:id])
  
    respond_to do |format|
      if @post_tags.update_attributes(params[:post_tag])
        format.html  { redirect_to(post_tags_url, :notice => 'Term Relationship was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @post_tags.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post_tags = PostTag.find(params[:id])
    @post_tags.destroy

    respond_to do |format|
       format.html { redirect_to post_tags_url }
       format.json { head :no_content }
    end
  end

  def post_tags_params
    params.fetch(:post_tag,{}).permit(:mini_post_id,:tag_id)
  end
  
  private
  def custom_layout
       if current_user.role? :admin  
        "dashboard"    
       else current_user.role? :user
        "welcome"
       end 
   end
end

app/views/post_tags/_form.html.erb
<%= form_for(@post_tags) do |f| %>
  <% if @post_tags.errors.any? %>
    <div  id="login-messages" class="ui-widget">
		<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
			<p align="center"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
			<strong class="error-counter"><%= pluralize(@post_tags.errors.count, t("error")) %> :</strong> </p>
			 <div id="error-list">
				 <% @post_tags.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      <br />
		      </div>
		</div>
	</div>
	<br />
  <% end %>
   <div class="field">
    <%= f.label t("id") %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label t("term_id") %><br />
    <%= f.text_field :term_id %>
  </div>
 <div class="field">
    <%= f.label t("taxonomy") %><br />
    <%= f.select(:taxonomy,options_for_select([
    	['Category', 'category'], 
		['Links Category', 'link_category'],
		['Quote Category', 'quote_category'],
		['Snippet Category', 'snippet_category'],
		['Nav Menu', 'nav_menu'],
		['Post Tag', 'post_tag'],
		['::choose::', '0']
		], '0'), :class =>  "d4xItem") %>

  </div>
 <div class="field">
    <%= f.label t("description") %><br />
    <%= f.text_field :description %>
  </div>
 <div class="field">
    <%= f.label t("parent") %><br />
    <%= f.text_field :parent %>
  </div>
 <div class="field">
    <%= f.label t("count") %><br />
    <%= f.text_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_tags/edit.html.erb
	<div id="text-content">
		<h2><%= t('Editing Term') %></h2>
		<%= render 'form' %>
		<%= link_to t('Show'), @post_tags %> |
		<%= link_to t('Back'), post_tags_path %>
	</div>

app/views/post_tags/index.html.erb
<div id="text-content">
		<h2><%= t('listing term taxonomies') %></h2>
		<br>
		<%= link_to t('new post_tags'), new_post_tag_path %>
		<br><br>
		<table width="100%">
		  <tr>
			<th align="left"><%=t(:id) %></th>
			<th align="left"><%=t(:post_id) %></th>
			<th align="left"><%=t(:tag_id) %></th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		 <% @post_tags.each do |post_tags| %>
		  <tr>
			<td><%= post_tags.id %></td>
			<td><%= post_tags.post_id %></td>
			<td><%= post_tags.tag_id %></td>
		    <td><%= link_to t('show'), post_tags %></td>
			<td>
			<% if can? :update, @post_tags %>  
				<%= link_to t('edit'), edit_post_tag_path(post_tags) %>
			<% end %>
			</td>
		    <td><% if can? :destroy, @post_tags %>  
					<%= button_to t('destroy'), post_tags, :confirm => 'are you sure?', :method => :delete %>
				<% end %>
			</td>
		  </tr>
		<% end %>
		</table>
</div>

app/views/post_tags/new.html.erb
<div id="text-content">
		<h2><%= t('New Post - Tag Relation') %></h2>
		<%= render 'form' %>
		<%= link_to t('Back'), post_tags_path %>
</div>

app/views/post_tags/show.html.erb
<div id="text-content">
		<p>
		  <b><%= t(:id) %></b><br>
		  <%= @post_tags.id %>
		</p>
		<p>
		  <b><%= t(:term_id) %></b><br>
		  <%= @post_tags.term_id %>
		</p>
		<p>
		  <b><%= t(:texonomy) %></b><br>
		  <%= @post_tags.taxonomy %>
		</p>
		<p>
		  <b><%= t(:description) %></b><br>
		  <%= @post_tags.description %>
		</p>
		<p>
		  <b><%= t(:parent) %></b><br>
		  <%= @post_tags.parent %>
		</p>
		<p>
		  <b><%= t(:count) %></b><br>
		  <%= @post_tags.count %>
		</p>
		<hr>
		<%= link_to t('edit'), edit_post_tag_path(@post_tags) %> |
		<%= link_to t('back'), post_tags_path %>
</div>